### ISSUE TITLE
Crashes when loading knxproj

### ISSUE THREAD

**Issue by henfri** [comcowo/OCTiS-Open#1]
Hello,

when trying to open my knxproj (I tried export from ETS4, 5 and 6) the tool just crashes without any message.
Unfortunately, I cannot find a logfile as well.
How can we debug this?

Regards,
Hendrik

**Comment by comcowo** [comment]
Hi Hendrik,
You could debug with Microsoft Visual Studio.
If you are not familiar with coding I could do this for you.
But I need your knxproj file to do so...

**Comment by henfri** [comment]
Hello,

sorry, I am not. 
I can send you my file. Can you send me your mail-adress?

Best regards,
Hendrik

**Comment by comcowo** [comment]
Ah sure: ow66@gmx.de

**Comment by comcowo** [comment]
Fixed in new relase v1.0.1
