### ISSUE TITLE
Kann die KNX Datei nicht laden

### ISSUE THREAD

**Issue by Amenophis86** [comcowo/OCTiS-Open#2]
Ich habe eine KNX Prod Datei, welche mit Passwort geschützt ist und Dateien im Anhang hat. ETS Version 5.7.7  So viel vorab. Diese Datei konnte nicht eingeladen werden. 

Habe jetzt mal nach und nach die Bedingungen geändert und festgestellt, dass wohl eine Passwort geschützte Datei nicht geöffnet werden kann. Deaktiviere ich das Passwort, kann sie eingelesen werden. Version des Programms wird mir beim Start 1.0.0.0 angezeigt. Runtergeladen habe ich jedoch die Version, welche hier auf git als 1.0.1 zum Download bereit steht.

**Comment by comcowo** [comment]
Danke für die Info. Passwortgeschützte KNX-Projektdateien werden nicht unterstützt.
Ich habe das im README-Text ergänzt und die Version für den nächsten Release angepasst.

**Comment by farmio** [comment]
Falls Interesse besteht passwortgeschützte Projekte in Zukunft zu unterstützen, hier ist ein Python-Beispiel wie man ETS 5 und 6 Projekte extrahiert: https://github.com/XKNX/xknxproject/blob/main/xknxproject/zip/extractor.py

**Comment by comcowo** [comment]
@farmio tolles Projekt. Vielleicht macht es ja Sinn, deinen Projektextrahierer in mein Tool einzubinden...

**Comment by farmio** [comment]
Nunja, die Idee war eigentlich xknxproject in HA zu benutzen um eine Projektdatei übers Frontend hochladen zu können und dann mittels https://github.com/XKNX/knx-frontend die Konfiguration übers UI machen zu können - so ähnlich wie dein Tool, allerdings nativ in HA (Core).
Über Unterstützung bei der Umsetzung würden wir uns sehr freuen 😉

Wenn du es auch in deinem Tool nutzen möchtest, bitte gerne!

**Comment by comcowo** [comment]
Ah verstehe, das ist natürlich noch besser.
Bin leider in Python völlig unwissend.

**Comment by farmio** [comment]
Der Python Teil ist dabei wohl wesentlich geringer als der TypeScript Teil 😉

Abgesehen davon ist Python recht Ein- und Umsteigerfreundlich 🐍 

Bei Interesse findest du uns am xknx Discord Server 👾👋
